# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5e3bcf05-e917-464d-bf02-3786ba8d2ec0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0ba6d855-9044-44a9-be42-0e27b90be262".device = "/dev/disk/by-uuid/0ba6d855-9044-44a9-be42-0e27b90be262";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A0EA-7075";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/media/data2" =
    { device = "/dev/disk/by-uuid/358995b3-330d-4268-8ac4-2ea7e6edc0a2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."data2".device = "/dev/disk/by-uuid/da5989ea-a8be-4693-aa0e-7f7f78554d4d";

  fileSystems."/media/data1" =
    { device = "/dev/disk/by-uuid/df673705-16b6-43a2-b38b-47c4c906ba14";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."data1".device = "/dev/disk/by-uuid/ef8de680-0070-4fab-8e96-4aa98868f8cf";

  #fileSystems."/media/data3" = {
  #  device = "/dev/disk/by-path/ip-192.168.0.11:3260-iscsi-iqn.2004-04.com.qnap:ts-464:iscsi.storage.82de6a";  # Replace with the correct device path after iSCSI login you cloud also do /dev/disk/by-uuid/<UUID-of-device>
  #  fsType = "ext4";  # Or the correct filesystem type
  #  options = [ "_netdev" "nofail" ];  # Ensures network is up before mounting and wont fail to boot if it cant connect
  #};

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp15s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
